name: Create Release on Push

on:
  push:
    branches:
      - main  # 监听推送到主分支的事件

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 从Secrets中获取TOKEN
        run: |
          # 使用GitHub API创建一个新的release
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "release",
              "target_commitish": "main",
              "name": "Release",
              "body": "Automatic release via GitHub Actions",
              "draft": false,
              "prerelease": false
            }'
